baseURL = 'https://obrepalski.com/'
languageCode = 'en'
theme = "blowfish"


enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = false

enableEmoji = true

[pagination]
pagerSize = 5

[imaging]
anchor = 'Center'

[taxonomies]
tag = "tags"
category = "categories"
author = "authors"
series = "series"

[sitemap]
changefreq = 'daily'
filename = 'sitemap.xml'
priority = 0.5

[params.author]
    name = "Paweł Obrępalski"
    headline = "Blog with my thoughts and experiences"
    bio = "Staff Engineer @ShareChat AI"
    image = "img/avatar.png"
    links = [
        {linkedin = "https://linkedin.com/in/obrepalski"},
        {github = "https://github.com/obrep"},
        {email = "mailto:pawel@obrepalski.com"}
    ]
